version: '3.7'
services:
  rhasspy:
      image: "rhasspy/rhasspy"
      restart: unless-stopped
      volumes:
          - "$PWD/.config/rhasspy/profiles:/profiles"
          - "/etc/localtime:/etc/localtime:ro"
      ports:
          - "12101:12101"
          - "12183:12183"
      devices:
          - "/dev/snd:/dev/snd"
      command: --user-profiles /profiles --profile de

  demo-skill:
    build: ./skills/demo

  get-time:
    build: ./skills/get-time

  shopping-list:
    build: ./skills/shopping-list
    environment:
      - TRELLO_API_BASE_URL=https://api.trello.com/1
      - TRELLO_OAUTH_CONSUMER_KEY=the-consumer-key
      - TRELLO_OAUTH_TOKEN=the-token
      - SHOPPING_LIST_TRELLO_BOARD_ID=the-board-id
      - SHOPPING_LIST_TRELLO_CARD_NAME=Shopping List

  weather:
    build: ./skills/weather

  static-answer:
    build: ./skills/static-answer