name: CI/CD pipeline

on: [push]

jobs:
  build-test-publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js 16.x
        uses: actions/setup-node@v1
        with:
          node-version: 16.x

      - name: Install dependencies
        run: npm ci

      - name: test
        run: |
          npm test
          npm run lint

      - name: build javascript
        run: npm run build

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push the get-time Docker image
        run: |
          docker build ./skills/get-time --tag ghcr.io/angelo-v/rhasspy-skill-get-time:latest
          docker push ghcr.io/angelo-v/rhasspy-skill-get-time:latest