name: CI/CD pipeline

on: [push]

jobs:
  build-test-publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js 16.x
        uses: actions/setup-node@v1
        with:
          node-version: 16.x

      - name: Install dependencies
        run: npm ci

      - name: test
        run: |
          npm test
          npm run lint

      - name: build javascript
        run: npm run build

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Available platforms
        run: echo ${{ steps.buildx.outputs.platforms }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push the get-time Docker image
        run: docker buildx build --push --platform=linux/amd64,linux/arm64,linux/arm/v7 ./skills/get-time --tag ghcr.io/angelo-v/rhasspy-skill-get-time:latest

      - name: Build and push the shopping-list Docker image
        run: docker buildx build --push --platform=linux/amd64,linux/arm64,linux/arm/v7 ./skills/shopping-list --tag ghcr.io/angelo-v/rhasspy-skill-shopping-list:latest

      - name: Build and push the weather Docker image
        run: docker buildx build --push --platform=linux/amd64,linux/arm64,linux/arm/v7 ./skills/weather --tag ghcr.io/angelo-v/rhasspy-skill-weather:latest

      - name: Build and push the static-answer Docker image
        run: docker buildx build --push --platform=linux/amd64,linux/arm64,linux/arm/v7 ./skills/static-answer --tag ghcr.io/angelo-v/rhasspy-skill-static-answer:latest